version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    environment:
      - REACT_APP_SERVER_DOMAIN=$SERVER_DOMAIN
      - REACT_APP_SERVER_PORT=$SERVER_PORT
    ports:
      - "3000:3000"
    volumes:
      - .:/home/node/app/frontend
      - node_modules:/home/node/app/frontend/node_modules

volumes:
  node_modules: