version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-prod
    container_name: frontend
    restart: unless-stopped
    env_file: .env
    environment:
      - NODE_ENV=production
    ports:
      - "80:80"