version: '3'

services:
  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      container_name: backend
      restart: unless-stopped
      env_file: .env
      environment:
        - NODE_ENV=development
        - MONGO_USERNAME=$MONGO_USERNAME
        - MONGO_PASSWORD=$MONGO_PASSWORD
        - MONGO_CLUSTER=$MONGO_CLUSTER
      ports:
        - "8080:8080"
      networks:
        - app-network
      volumes:
        - ./backend:/home/node/app/backend
        - node_modules:/home/node/app/backend/node_modules  

  frontend:
      build:
        context: ./frontend
        dockerfile: Dockerfile
      container_name: frontend
      restart: unless-stopped
      #env_file: .env
      environment:
        - NODE_ENV=development
      #  - MONGO_USERNAME=$MONGO_USERNAME
      #  - MONGO_PASSWORD=$MONGO_PASSWORD
      #  - MONGO_CLUSTER=$MONGO_CLUSTER
      ports:
        - "80:3000"
      networks:
        - app-network
      volumes:
        - ./frontend:/home/node/app/frontend
        - node_modules:/home/node/app/frontend/node_modules


networks:
  app-network:
    driver: bridge
volumes:
  node_modules: