version: '3.7'

services:

  frontend:
    container-name: frontend
    build: './frontend'
    depends_on:
      - backend
      - mongo

  backend:
    container-name: backend
    build: './backend'
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    container-name: mongo
    image: mongo:4.2.2-bionic
    ports:
      - "27017:27017"