version: '3'
services:
  frontend:
    build: './frontend'
    ports:
      - "80:3000"
    depends_on:
      - backend
      - mongo

  backend:
    build: './backend'
    depends_on:
      - mongo
    links:
      - mongo

  mongo:
    image: mongo:4.2.2-bionic
    ports:
      - "27017:27017"
