version: '3'

services:
  backend:
      build:
        context: ./backend
        dockerfile: Dockerfile
      container_name: backend
      restart: unless-stopped
      env_file: .env
      environment:
        - MONGO_USERNAME=$MONGO_USERNAME
        - MONGO_PASSWORD=$MONGO_PASSWORD
        - MONGO_CLUSTER=$MONGO_CLUSTER
      ports:
        - "8080:8080"
      network_mode: bridge
      volumes:
        - ./backend:/home/node/app/backend
        - ./backend/node_modules:/home/node/app/backend/node_modules  

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    environment:
      - REACT_APP_SERVER_DOMAIN=$SERVER_DOMAIN
      - REACT_APP_SERVER_PORT=$SERVER_PORT
    ports:
      - "3000:3000"
    network_mode: bridge
    volumes:
      - ./frontend:/home/node/app/frontend
      - ./frontend/node_modules:/home/node/app/frontend/node_modules

volumes:
  node_modules: